### PR TITLE
add docs how to install sox using conda

### PR DESCRIPTION
**Pull request by faroit**
Describe how to install sox using conda package manager

### CODE REVIEW

**Comment by faroit** [comment]
This issue should be fixed as part of the audiomate JOSS review https://github.com/openjournals/joss-reviews/issues/2135

**Comment by ynop** [comment]
Thanks for the improvement and your review!

Could you also add the description in the sphinx documentation at https://github.com/ynop/audiomate/blob/master/docs/notes/installation.rst?

**Comment by faroit** [comment]
> Could you also add the description in the sphinx documentation at https://github.com/ynop/audiomate/blob/master/docs/notes/installation.rst?

sure

**Comment by faroit** [comment]
ready

**Pull request merged**
