### PR TITLE
Show tatoeba process

### PR DESCRIPTION
**Pull request by DanBmh**
I also changed the label type, because this solved a problem i had and the other datasets seemed to have LL_WORD_TRANSCRIPT as default and LL_WORD_TRANSCRIPT_RAW only optionally.

### CODE REVIEW

**Comment by DanBmh** [comment]
Ok, i will move the LL_WORD_TRANSCRIPT commit to another branch. What about the updated comment, shall i make a third pull request for it?

Regarding the tqdm and print suggestions, you are using both in the other files, for example [here](https://github.com/ynop/audiomate/blob/master/audiomate/corpus/conversion/base.py), so i thought it would be ok to use them too.

**Comment by aahlenst** [comment]
In my opinion, you can do the comment together with `LL_WORD_TRANSCRIPT`.

Regarding tqdm/printing, I'm sorry that it hit you. Let's see what @ynop has to say.

**Comment by ynop** [comment]
I added those things when I needed it.
But, @aahlenst is right, it is not a good solution.
I guess we should find a better way to do it.

**Comment by DanBmh** [comment]
I would suggest then we merge this with tqdm and print and you find a better way some other time:)

**Comment by aahlenst** [comment]
@DanBmh #114 brought the necessary infrastructure for logging. Care to update your PR?

**Comment by DanBmh** [comment]
Do you plan to implement a prediction for the time to completion in your logger? 
I found this helpful in very long running tasks (>4h).

**Comment by ynop** [comment]
No plans so far.
But would be easy to implement based on the 5 minute logging cycle and nice to have.
If you'd like to do it, you can add it and open a PR.

**Comment by ynop** [comment]
Could you merge the two commits? Afterwards I can merge it.

**Comment by DanBmh** [comment]
Done. Why didn't you merge this before updating the logging?

**Comment by ynop** [comment]
Because, I didn't think about that before merging the logging.
And it is cleaner instead of introducing more "bad examples" and correct it right again.

**Pull request merged**
