### PR TITLE
Check for invalid utterances in mailabs. Update tuda invalid utterances.

### PR DESCRIPTION
**Pull request by DanBmh**

### CODE REVIEW

**Comment by ynop** [comment]
Hi Dan

Thanks for the contribution.
Could you please rebase your branch onto the master instead of merging?
Otherwise we end up with unnecessary merge commits.
I'm happy to help out, if needed.

Let me know when your done, so I can merge.

**Comment by DanBmh** [comment]
Sorry i forgot this
Now it should be better
I hope you don't mind the two different git accounts ...

**Comment by ynop** [comment]
Are you planning to add more?
I want to create a new release and would be cool to have this changes in there.

It seems that there are missing some commas, forcing some tests to fail.

**Comment by DanBmh** [comment]
Right, i missed one comma. Added it now.

I switched to another way to sort out invalid files as i did not find a way to exclude them with audiomate without recreating the dataset and converting the audiofiles again.
Also it was easier for me as i could copy the path i got from my error message to my file without adjusting it differently for each dataset.

You can find my new invalid files here:
https://github.com/DanBmh/deepspeech-german/blob/master/data/dataset_operations.py

It will take me some time to find all the invalid files as i have to rerun a training every time, sort out some files and rerun the training again.

**Comment by ynop** [comment]
Ok, makes sense.
If you could let me know, when you have a final list of invalid files, that would be cool.

**Pull request merged**
